version: '2'
services:
  yj_web:
    container_name: wechat
    image: wechat:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    ports:
      - "10000:10000"
    volumes:
      - ./:/conf
      #    environment:
      #      - --spring.config.location=/conf/application.yml
      #      - --spring.profiles.active=test